# Analysis options for Flutter apps
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - ios/**
    - android/**
    - web/**
  
  errors:
    # Make certain warnings into errors for production code
    missing_required_param: error
    missing_return: error
    dead_code: error
    
linter:
  rules:
    # Essential rules for production code
    - annotate_overrides
    - avoid_print
    - avoid_unnecessary_containers
    - cancel_subscriptions
    - close_sinks
    - curly_braces_in_flow_control_structures
    - empty_statements
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables  
    - prefer_final_fields
    - prefer_single_quotes
    - unnecessary_new
    - unnecessary_this
    - use_rethrow_when_possible
